[features]
seeds = false
skip-lint = false
[programs.devnet]
minter = "YJFLxAasyQrfxEqNzvcb2QKX1x2Xmgxcv61AgQuciay"
reward_dist = "ADrM2jnS2kFVfQYqjGmnXU9bZom89eKZKpJBf4FjDgi2"
emission_dist = "ADrM2jnS2kFVfQYqjGmnXU9bZom89eKZKpJBf4FjDgi3"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mouazzama/new_program-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true
