[features]
seeds = false
skip-lint = false
[programs.localnet]
minter = "ADrM2jnS2kFVfQYqjGmnXU9bZom89eKZKpJBf4FjDgio"
reward_dist = "ADrM2jnS2kFVfQYqjGmnXU9bZom89eKZKpJBf4FjDgi2"
emission_dist = "ADrM2jnS2kFVfQYqjGmnXU9bZom89eKZKpJBf4FjDgi3"
staking = "ADrM2jnS2kFVfQYqjGmnXU9bZom89eKZKpJBf4FjDg45"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mouazzama/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
