[features]
seeds = false
skip-lint = false
[programs.devnet]
staking = "BFwmbEmjJfeomE29k5dj2BXeXEGo168fVKEFR3MtwPoB"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mouazzama/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
